package dev.nuculabs.keyworder.core;

import java.util.Arrays;
import java.util.List;

public class Keywords {
    public static List<String> KEYWORDS = Arrays.asList(
        "abandoned",
        "abstract",
        "adult",
        "adventure",
        "aerial",
        "aerial view",
        "aerospace industry",
        "africa",
        "agricultural field",
        "agriculture",
        "air show",
        "air vehicle",
        "aircraft wing",
        "airplane",
        "airport",
        "airshow",
        "alone",
        "alpha",
        "alpine",
        "alps",
        "ancient",
        "animal",
        "antique",
        "architectural column",
        "architectural dome",
        "architecture",
        "arid climate",
        "art",
        "asia",
        "asian",
        "astronomy",
        "athlete",
        "aurora borealis",
        "aurora polaris",
        "autumn",
        "aviation",
        "background",
        "backgrounds",
        "balance",
        "ballet",
        "balloon",
        "bathroom",
        "beach",
        "beautiful",
        "beauty",
        "bedroom",
        "bee",
        "beetle",
        "bicycle",
        "big cat",
        "bikini",
        "bird",
        "bird of prey",
        "birds",
        "black",
        "black and white",
        "black color",
        "blackandwhite",
        "blonde",
        "blossom",
        "blue",
        "blue hour",
        "blurred motion",
        "bnw",
        "boat",
        "body",
        "bokeh",
        "bonding",
        "botany",
        "boudoir",
        "boy",
        "boys",
        "bra",
        "bright",
        "brown",
        "brunette",
        "building",
        "building exterior",
        "built structure",
        "bumper",
        "bus",
        "business",
        "cable car",
        "candid",
        "canine",
        "canon",
        "canyon",
        "car",
        "car show",
        "care",
        "carefree",
        "cargo container",
        "castle",
        "casual clothing",
        "cathedral",
        "catholicism",
        "caucasian",
        "celebration",
        "chair",
        "cheerful",
        "child",
        "christianity",
        "chrome",
        "church",
        "city",
        "city life",
        "cityscape",
        "classic",
        "cliff",
        "close up",
        "closeup",
        "clothing",
        "cloud",
        "clouds",
        "cloudscape",
        "coast",
        "coastline",
        "collector's car",
        "color",
        "colorful",
        "colors",
        "comfortable",
        "commercial dock",
        "commuter",
        "composition",
        "concept",
        "confidence",
        "connection",
        "constellation",
        "construction industry",
        "container",
        "container ship",
        "convertible",
        "cool attitude",
        "couple",
        "cozy",
        "creative",
        "culture",
        "cultures",
        "curtain",
        "curve",
        "cut out",
        "cute",
        "cycling",
        "daisy",
        "dancing",
        "danger",
        "daniel laan",
        "dark",
        "dawn",
        "day",
        "daylight",
        "decoration",
        "deer",
        "desert",
        "design",
        "desire",
        "destination",
        "deutschland",
        "diminishing perspective",
        "direction",
        "dog",
        "dolomites",
        "domestic bathroom",
        "domestic cat",
        "domestic life",
        "domestic room",
        "door",
        "downtown district",
        "dragonfly",
        "dramatic",
        "dramatic sky",
        "dress",
        "drink",
        "driving",
        "drone",
        "drop",
        "dusk",
        "electric guitar",
        "elegance",
        "embracing",
        "engine",
        "enjoyment",
        "environment",
        "epic",
        "erotic",
        "europe",
        "evening",
        "evening gown",
        "event",
        "exercising",
        "exhibition",
        "exploration",
        "eyes",
        "facade",
        "face",
        "fall",
        "family",
        "famous place",
        "fantasy",
        "farm",
        "fashion",
        "fashionable",
        "feather",
        "feline",
        "female",
        "femininity",
        "fender",
        "field",
        "fighter plane",
        "film",
        "fitness",
        "five people",
        "flexibility",
        "flight",
        "flower",
        "flower head",
        "flowering plant",
        "flowers",
        "flowing",
        "flowing water",
        "flying",
        "focus on foreground",
        "fog",
        "food",
        "food and drink",
        "forest",
        "formalwear",
        "fort",
        "four people",
        "fragility",
        "france",
        "freedom",
        "freight transportation",
        "french culture",
        "fresh",
        "freshness",
        "friendship",
        "front view",
        "fruit",
        "fuel and power generation",
        "fujifilm",
        "full length",
        "fun",
        "fungus",
        "galaxy",
        "garden",
        "geology",
        "germany",
        "girl",
        "girls",
        "glacier",
        "glamour",
        "glendor",
        "glowing",
        "gothic style",
        "grace",
        "grass",
        "green",
        "green color",
        "growth",
        "guitar",
        "hair",
        "handsome",
        "handsome people",
        "happiness",
        "happy",
        "harbor",
        "hat",
        "headlight",
        "headshot",
        "healthy",
        "healthy lifestyle",
        "heron",
        "high angle view",
        "high heels",
        "hiking",
        "hill",
        "history",
        "holiday",
        "home",
        "horizon",
        "horizon over water",
        "horse",
        "house",
        "human",
        "ice",
        "iceland",
        "idyllic",
        "illuminated",
        "illustration",
        "image focus technique",
        "in bloom",
        "individuality",
        "indoor",
        "indoors",
        "industry",
        "inflorescence",
        "innocence",
        "insect",
        "invertebrate",
        "islam",
        "island",
        "italian",
        "italian culture",
        "italy",
        "japan",
        "jeans",
        "journey",
        "joy",
        "laanscapes",
        "lake",
        "land",
        "land vehicle",
        "landmark",
        "landscape",
        "large",
        "leaf",
        "legs",
        "leisure activity",
        "lepidoptera",
        "life",
        "lifestyle",
        "lifestyles",
        "light",
        "lighthouse",
        "lighting equipment",
        "lights",
        "lingerie",
        "locomotive",
        "long exposure",
        "looking",
        "looking at camera",
        "love",
        "low angle view",
        "lush foliage",
        "luxury",
        "lying down",
        "macro",
        "majestic",
        "male",
        "malemodel",
        "mammal",
        "man",
        "mature men",
        "mature women",
        "meadow",
        "medieval",
        "medium group of people",
        "metal",
        "mid adult men",
        "mid adult women",
        "midsection",
        "military",
        "military airplane",
        "milky way",
        "minimal",
        "mist",
        "mode of transport",
        "model",
        "modern",
        "monochrome",
        "monument",
        "mood",
        "moody",
        "moon",
        "moored",
        "morning",
        "moss",
        "motion",
        "motor vehicle",
        "motorcycle",
        "mountain",
        "multi colored",
        "museum",
        "mushroom",
        "music",
        "musical instrument",
        "naked",
        "natural",
        "natural light",
        "nature",
        "nautical vessel",
        "nebula",
        "new",
        "night",
        "nightscape",
        "no people",
        "northern lights",
        "norway",
        "nostalgia",
        "nude",
        "nyc",
        "obsolete",
        "ocean",
        "office building exterior",
        "old",
        "on the move",
        "one",
        "one adult only",
        "one person",
        "orange",
        "orange color",
        "outdoor",
        "outdoors",
        "outer space",
        "owl",
        "palace",
        "panorama",
        "panoramic",
        "panties",
        "paris",
        "park",
        "passenger craft",
        "passion",
        "pattern",
        "peak",
        "people",
        "perching",
        "performance",
        "person",
        "petal",
        "pets",
        "photo",
        "pier",
        "pink",
        "pink color",
        "place of worship",
        "plane",
        "planespotter",
        "planespotting",
        "plant",
        "plant stem",
        "playing",
        "plucking an instrument",
        "poland",
        "pollen",
        "pollination",
        "portrait",
        "posing",
        "pretty",
        "propeller",
        "protection",
        "public park",
        "public transportation",
        "purebred dog",
        "purple",
        "rail transportation",
        "railroad station",
        "railroad station platform",
        "railroad track",
        "rain",
        "real",
        "rear view",
        "red",
        "reflection",
        "reflections",
        "relaxation",
        "religion",
        "remote location",
        "residential building",
        "residential district",
        "restaurant",
        "resting",
        "retail",
        "retro",
        "retro style",
        "riding",
        "river",
        "road",
        "rock",
        "rock formation",
        "rock music",
        "rocks",
        "romance",
        "romantic",
        "rooftop",
        "rural scene",
        "rusty",
        "sail",
        "sailboat",
        "sailing",
        "sand",
        "sand dune",
        "scenery",
        "scenic",
        "scenics",
        "science",
        "sea",
        "sea bird",
        "seascape",
        "season",
        "seduction",
        "seductive women",
        "selective focus",
        "senior men",
        "sensual",
        "sensuality",
        "serious",
        "sexy",
        "shadow",
        "shadows",
        "shiny",
        "ship",
        "shipping",
        "shopping",
        "shore",
        "silhouette",
        "single flower",
        "sitting",
        "skin",
        "sky",
        "skyscraper",
        "small",
        "smile",
        "smiling",
        "snow",
        "sofa",
        "songbird",
        "space and astronomy",
        "spain",
        "speed",
        "spirituality",
        "splashing",
        "sport",
        "sports car",
        "sports clothing",
        "sports training",
        "spotter",
        "spread wings",
        "spring",
        "springtime",
        "staircase",
        "stairs",
        "stamen",
        "standing",
        "star field",
        "stars",
        "station",
        "stationary",
        "steam",
        "steam train",
        "stockings",
        "stone material",
        "store",
        "storm",
        "street",
        "strength",
        "stretching",
        "string instrument",
        "striped",
        "studio",
        "studio shot",
        "style",
        "suit",
        "summer",
        "sun",
        "sunglasses",
        "sunlight",
        "sunny",
        "sunrise",
        "sunset",
        "swimming",
        "swimming pool",
        "swimwear",
        "switzerland",
        "technology",
        "teenage boys",
        "teenage girls",
        "texture",
        "the way forward",
        "three people",
        "tits",
        "toadstool",
        "together",
        "togetherness",
        "tokyo",
        "top",
        "topless",
        "tourism",
        "tower",
        "town",
        "tradition",
        "traditional",
        "traffic",
        "train",
        "tranquil",
        "transportation",
        "travel",
        "travel destinations",
        "tree",
        "tree trunk",
        "trees",
        "trip",
        "tropical",
        "tropical climate",
        "twilight",
        "two",
        "two people",
        "umbrella",
        "uncultivated",
        "undersea",
        "underwater",
        "underwear",
        "urban",
        "urban skyline",
        "usa",
        "vacation",
        "vacations",
        "valley",
        "view",
        "village",
        "vintage",
        "vintage car",
        "vitality",
        "vulnerability",
        "waist up",
        "walking",
        "wall",
        "wallpaper",
        "warm",
        "warm clothing",
        "water",
        "water bird",
        "waterfall",
        "waterfront",
        "waves",
        "weather",
        "wedding",
        "wedding dress",
        "wellbeing",
        "wet",
        "wheel",
        "white",
        "white background",
        "white color",
        "wild",
        "wilderness",
        "wildlife",
        "wind",
        "window",
        "winter",
        "woman",
        "women",
        "woodland",
        "woods",
        "yacht",
        "yellow",
        "yoga",
        "young"
    );
}
